### PR TITLE
Update README to include static assets

### PR DESCRIPTION
**Pull request by digitalfx**

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Do you think we should change it to `resources/public`? If someone wanted `mydomain.com/assets/something.js` they'd have to do `resources/assets/assets`.

**Comment by digitalfx** [comment]
Yes, that would seem to be consistent with node.js and Sinatra examples. (Although equally then you could say if someone wanted `mydomain.com/public/photo.jpg` they'd have to use `resources/public/public` :wink:)

**Comment by jamonholmgren** [comment]
Let's do it. I think `assets/` is a pretty normal thing.

**Comment by jamonholmgren** [comment]
Oops, should I have merged this @digitalfx ? I apparently lost track of it.

**Comment by digitalfx** [comment]
Don't worry, I just went through and cleared any pull requests that were going stale, nothing important.

**Pull request closed without merging**
